# Generated by Django 3.2.25 on 2024-07-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stree_address2',
            new_name='street_address2',
        ),
    ]
