# Generated by Django 3.2.25 on 2024-07-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge_url',
            new_name='image_url',
        ),
    ]
